name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install cx_Freeze
        
    - name: Create assets directory
      run: |
        mkdir assets
        echo "Creating placeholder icon..."
        
    - name: Build executable
      run: |
        python setup.py build
        
    - name: Install NSIS
      run: |
        choco install nsis -y
        
    - name: Create installer
      run: |
        makensis installer.nsi
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: YysADBToolbox-Windows
        path: |
          YysADBToolbox_v*_Setup.exe
          build/exe/
          
  release:
    needs: build-windows
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: YysADBToolbox-Windows
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          YysADBToolbox_v*_Setup.exe
        body: |
          ## 奕奕ADB工具箱 ${{ github.ref_name }}
          
          ### 新功能
          - 完整的ADB工具集成
          - 现代化GUI界面
          - 设备连接管理
          - 文件传输功能
          - 应用管理工具
          - 系统监控功能
          
          ### 安装说明
          1. 下载 `YysADBToolbox_v*_Setup.exe`
          2. 以管理员身份运行安装程序
          3. 按照向导完成安装
          4. 启动程序开始使用
          
          ### 系统要求
          - Windows 10/11
          - .NET Framework 4.7.2+
          - USB调试驱动
          
          ### 问题反馈
          如有问题或建议，请在GitHub Issues中提交
          
          感谢使用奕奕ADB工具箱！
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
